### PR TITLE
Conventional commits

### PR DESCRIPTION
**Pull request by ngonzalezpazFC**

### CODE REVIEW

**Comment by javier-godoy** [comment]
https://github.com/FlowingCode/VerticalMenuAddon/commit/6ef7066a16869cecbd95ee49e0cee177cab4f765 build: add junit dependency and maven surefire plugin

**Comment by ngonzalezpazFC** [comment]
> [6ef7066](https://github.com/FlowingCode/VerticalMenuAddon/commit/6ef7066a16869cecbd95ee49e0cee177cab4f765) build: add junit dependency and maven surefire plugin

Done

**Comment by javier-godoy** [comment]
0dc9747e875f61a721f708c164aa8e7241e00f94 refactor(demo): edit demo route
7965e33c5a55dd5396ffb38df73994822657d4e3 ci(demo): add demo-jar profile

The change to assembly.xml goes into 7965e33c5a55dd5396ffb38df73994822657d4e3 (ci) instead of 1ebc641ed4ed8db6c8aac7352e2b3183588e1b62 (test)

**Comment by ngonzalezpazFC** [comment]
> 
> 
> [0dc9747](https://github.com/FlowingCode/VerticalMenuAddon/commit/0dc9747e875f61a721f708c164aa8e7241e00f94) refactor(demo): edit demo route
> [7965e33](https://github.com/FlowingCode/VerticalMenuAddon/commit/7965e33c5a55dd5396ffb38df73994822657d4e3) ci(demo): add demo-jar profile
> 
> The change to assembly.xml goes into [7965e33](https://github.com/FlowingCode/VerticalMenuAddon/commit/7965e33c5a55dd5396ffb38df73994822657d4e3) (ci) or as a standalone commit, instead of piggybacking [1ebc641](https://github.com/FlowingCode/VerticalMenuAddon/commit/1ebc641ed4ed8db6c8aac7352e2b3183588e1b62) (test)
> 
> [6ae66d7](https://github.com/FlowingCode/VerticalMenuAddon/commit/6ae66d75be8082c5a8c261181f4952547875a16d) docs: add release note
> (Addons projects define the scope demo for those changes affecting the demo source code; other changes use the unnamed scope).

Done

**Comment by ngonzalezpazFC** [comment]
> 
> 
> > [0dc9747](https://github.com/FlowingCode/VerticalMenuAddon/commit/0dc9747e875f61a721f708c164aa8e7241e00f94) refactor(demo): edit demo route
> > [7965e33](https://github.com/FlowingCode/VerticalMenuAddon/commit/7965e33c5a55dd5396ffb38df73994822657d4e3) ci(demo): add demo-jar profile
> > The change to assembly.xml goes into [7965e33](https://github.com/FlowingCode/VerticalMenuAddon/commit/7965e33c5a55dd5396ffb38df73994822657d4e3) (ci) or as a standalone commit, instead of piggybacking [1ebc641](https://github.com/FlowingCode/VerticalMenuAddon/commit/1ebc641ed4ed8db6c8aac7352e2b3183588e1b62) (test)
> > [6ae66d7](https://github.com/FlowingCode/VerticalMenuAddon/commit/6ae66d75be8082c5a8c261181f4952547875a16d) docs: add release note
> > (Addons projects define the scope demo for those changes affecting the demo source code; other changes use the unnamed scope).
> 
> Done

Done cherry picking last master [commit](https://github.com/FlowingCode/VerticalMenuAddon/pull/8/commits/3ef49ce6ebc257ed786f2ec54c2383099f5fc40b)

**Comment by javier-godoy** [comment]
Discard. We'll start applying conventional commits since the next release.

**Pull request closed without merging**
